FROM python:3.12

COPY requirements/requirements.process.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir --default-timeout=1500 -r /tmp/requirements.txt \
    && rm -rf /tmp/requirements.txt

COPY . /app
WORKDIR /app

