FROM nvcr.io/nvidia/pytorch:24.04-py3

COPY requirements/requirements.train.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt \
    && rm -rf /tmp/requirements.txt

COPY . /app
WORKDIR /app
