FROM python:3.12

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
        hmmer \
    && apt-get clean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/requirements.process.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir --default-timeout=1500 -r /tmp/requirements.txt \
    && rm -rf /tmp/requirements.txt

COPY . /app
WORKDIR /app

